$ErrorActionPreference = 'Stop'
$path = Join-Path $PSScriptRoot '..\src\pages\CompetitiveModePage.jsx'
$text = Get-Content -Raw -Encoding UTF8 $path

$targetPattern = '(?s)function TargetCard\(\{ target, ready, shared = Boolean\(target\?\.teamId\), mode = ''own'' \}\) \{.*?\nfunction RoomCodeCard'
$targetReplacement = @'
function TargetCard({ target, ready, shared = Boolean(target?.teamId), mode = 'own', opponentTeamLabel = 'OPPONENT TEAM' }) { const isOpponent = mode === 'opponent'; return <section className="glass-panel rounded-2xl overflow-hidden border border-primary-fixed/30 bg-primary-fixed/5" aria-label={`${opponentTeamLabel} target`}><div className="px-4 py-3 border-b border-white/10 flex items-center gap-2"><span className="material-symbols-outlined text-primary-fixed" aria-hidden="true">{isOpponent ? 'visibility' : shared ? 'groups' : 'lock'}</span><span className="font-label-caps text-label-caps text-primary-fixed">{isOpponent ? `${opponentTeamLabel} TARGET` : shared ? 'TEAM TARGET' : 'YOUR SECRET TARGET'}</span></div>{target && ready ? <div className="p-4 flex items-center gap-4"><img src={target.image} alt={target.name} className="w-24 h-24 shrink-0 rounded-xl object-cover border-2 border-primary-fixed/40" /><div><div className="font-headline-sm text-white">{target.name}</div></div></div> : <div className="p-6 text-center text-on-surface-variant">Synchronizing target…</div>}</section>; }
function RoomCodeCard
'@
$text = [regex]::Replace($text, $targetPattern, $targetReplacement, 1)

$guessPattern = '(?s)function GuessGrid\(\{.*?\nfunction TeamScoreboard'
$guessReplacement = 'function TeamScoreboard'
$text = [regex]::Replace($text, $guessPattern, $guessReplacement, 1)

$gamePattern = '(?s)function TeamBattleGameplay\(\{ state, actions \}\) \{.*?\nfunction BracketMatch'
$gameReplacement = @'
function TeamBattleIdentity({ state, actions }) { const myTeam = Object.values(state.teams || {}).find((team) => team.playerIds.includes(actions.playerId)); const myLabel = myTeam?.teamId === 'team_a' ? 'TEAM A' : 'TEAM B'; return <section className="rounded-2xl border border-white/10 bg-white/5 p-4" aria-label="Your team"><div className="flex items-center justify-between gap-3"><span className="font-label-caps text-label-caps text-primary-fixed">{myLabel}</span><span className="text-xs text-on-surface-variant">YOUR TEAM</span></div><div className="mt-3 grid grid-cols-2 gap-2">{myTeam?.playerIds.map((id) => <div key={id} className="rounded-xl border border-white/10 bg-black/15 px-3 py-2 text-sm text-white truncate">{state.players[id]?.name || id}</div>)}</div></section>; }
function TeamBattleGameplay({ state, actions }) { const myTeam = Object.values(state.teams || {}).find((team) => team.playerIds.includes(actions.playerId)); const myLabel = myTeam?.teamId === 'team_a' ? 'TEAM A' : 'TEAM B'; const opponentLabel = myLabel === 'TEAM A' ? 'TEAM B' : 'TEAM A'; const lockedConfirmationTeam = state.match?.confirmationTeamId || null; const myTeamRequired = Boolean(lockedConfirmationTeam && myTeam?.teamId === lockedConfirmationTeam); const confirmations = state.match?.confirmations?.[myTeam?.teamId] || {}; const confirmedIds = myTeam?.playerIds.filter((id) => confirmations[id]?.roundNumber === state.roundNumber && confirmations[id]?.matchId === state.match?.matchId) || []; const hasConfirmed = confirmedIds.includes(actions.playerId); const requiredTeamsComplete = Boolean(lockedConfirmationTeam && myTeamRequired && myTeam?.playerIds?.length === 2 && myTeam.playerIds.every((id) => confirmations[id]?.roundNumber === state.roundNumber && confirmations[id]?.matchId === state.match?.matchId)); useEffect(() => { if (requiredTeamsComplete && state.hostId === actions.playerId) actions.resolveTeamRound(); }, [requiredTeamsComplete, state.hostId, actions]); return <div className="space-y-5"><div className="rounded-2xl border border-white/10 bg-black/15 p-4 sm:p-5"><p className="font-label-caps text-label-caps text-primary-fixed">2v2 TEAM BATTLE · ROUND {state.roundNumber} / 3</p><h2 className="font-display-lg text-display-lg text-white mt-1">{state.category}</h2></div><TeamBattleIdentity state={state} actions={actions} /><TargetCard target={actions.privateTarget} ready={actions.targetReady} mode="opponent" opponentTeamLabel={opponentLabel} /><section className="glass-panel-heavy rounded-2xl p-4 sm:p-5 border border-secondary-fixed/30 bg-secondary-fixed/5 shadow-[0_18px_60px_rgba(0,0,0,0.2)]" aria-label="Team confirmation"><div className="flex items-center justify-between gap-3"><span className="font-label-caps text-label-caps text-secondary-fixed">{opponentLabel} GUESSED CORRECT</span><span className="text-xs text-on-surface-variant">{confirmedIds.length}/2 CONFIRMED</span></div><button type="button" disabled={!myTeamRequired || hasConfirmed || !actions.canMutateCompetitive} onClick={() => actions.confirmTeamGuess()} className={`touch-feedback mt-4 min-h-14 w-full rounded-2xl px-4 py-4 font-headline-sm transition-all active:scale-[0.99] focus-visible:outline-none focus-visible:ring-2 focus-visible:ring-secondary-fixed disabled:cursor-not-allowed ${hasConfirmed ? 'border border-primary-fixed/50 bg-primary-fixed/10 text-primary-fixed' : 'bg-secondary-fixed text-on-secondary-fixed hover:brightness-110 disabled:opacity-40'}`}><span className="material-symbols-outlined align-middle mr-2" aria-hidden="true">{hasConfirmed ? 'verified' : 'check_circle'}</span>{hasConfirmed ? `CONFIRMED · ${confirmedIds.length}/2` : `${opponentLabel} GUESSED CORRECT`}</button></section></div>; }
function BracketMatch
'@
$text = [regex]::Replace($text, $gamePattern, $gameReplacement, 1)

$tempPath = "$path.tmp"
Set-Content -Path $tempPath -Value $text -Encoding UTF8
Move-Item -Force -Path $tempPath -Destination $path
Write-Output 'Team Battle UI patch applied.'
